
server:
  port: 8081
eureka:
  instance:
    hostname: eureka1.hewe.vip
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka2.hewe.vip:8082/eureka/,http://eureka3.hewe.vip:8083/eureka/
spring:
  application:
    name: eureka-center